name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3  # GitHub Action to checkout the repo
        
      # Step 2: Set up Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7  # Use the specified Python version

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to avoid any issues
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-python-app .  # Replace 'my-python-app' with your image name

      # Step 5: Install Railway CLI
      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh  # Install Railway CLI

      # Step 6: Set the Railway API key and Deploy to Railway
      - name: Deploy to Railway
        run: |
          export RAILWAY_API_KEY=737dee2d-09da-45e4-a88d-ddd084ca491b  # Set API key as an environment variable
          railway up -- --docker  # Deploy the Docker image to Railway
